
// Automatically generated by configure.py, do not edit
.n64                                   // Tell armips we're targeting N64
.open "rom/rockmandash.z64", "rom/rockmandash.mod.z64", 0
.definelabel PAYLOAD_ROM,  0x1FE0780
.definelabel PAYLOAD_VRAM, 0x80400000
.include "asm\boot.asm"
.include "asm\mainHook.asm"
.include "asm\symbols.asm"

.headersize PAYLOAD_VRAM - PAYLOAD_ROM
.org PAYLOAD_VRAM
PAYLOAD_START_RAM:
.include "asm\extraFuncs.s"
.importobj "obj\crash.o"
.importobj "obj\gfx.o"
.importobj "obj\graphics.o"
.importobj "obj\main.o"
.importobj "obj\savestate.o"
.importobj "obj\timer.o"

.align 8
PAYLOAD_END_RAM:
.close
